### ISSUE TITLE
TODO: tests

### ISSUE THREAD

**Issue by IonicArgon** [Discobots-1104A/2021-2022-kidney-failure#1]
need to test a few things related to logic

### PID controller
things that we need to check are:
- [x] actually works (makes robot move)
- [x] tuning range
- [ ] if the filtering makes a difference

### Trapezoidal Motion Profile
things that we need to check are:
- [ ] does it work w/ the PID as part of feedforward + feedback
- [ ] can we use it in any situation besides just movement

### Utility
things we need to check are:
- [ ] can we perform asynchronous actions w/ Async
- [ ] does the Timer work (this should be like the simplest one to check)

in order to check for these, we're gonna have to write some code to test it.
gonna require the following:
- [x] basic drive code functionality so we can actually control the robot
- [ ] basic logging class to log stuff onto a file in the sd card on the robot
- [ ] basic autonomous code to test all the logic with
- [ ] initialization code (this is obvious)

**Comment by IonicArgon** [comment]
pid works with the lift so it should work with the drive

filtering has not been tested yet
