### ISSUE TITLE
TODO: change motion profile from pure trapezoid to s-curved trapezoid

### ISSUE THREAD

**Issue by IonicArgon** [Discobots-1104A/2021-2022-kidney-failure#2]
a pure trapezoidal motion profile does not take into account jerk (the derivative of acceleration)
in a pure trapezoidal profile, jerk would be infinite at the phase transitions (which makes the robot not so smooth while moving)

for now, we'll use a pure trapezoid but later we should create a class SCurveMotion for proper motion profiling

### what we gotta do
- [ ] do research into s-curve motion profile controllers and the math behind it
  - [ ] think that requires some spline math, so something new to learn
  - [ ] maybe look at FRC examples for this too
- [ ] implement the darn thing
- [ ] test it after we implement it
